version: '3.8'

services:
  app:
    image: php:8-fpm
    container_name: php_app
    volumes:
        - ./app:/var/www/html
    networks:
        - app-network
    depends_on:
        - redis
        - rabbitmq

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./app:/var/www/html
    ports:
        - "80:80"
        - "443:443"
    networks:
        - app-network
    depends_on:
        - app

  redis:
    image: redis:latest
    container_name: redis
    networks:
        - app-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
        - "15672:15672" # RabbitMQ Management UI
        - "5672:5672"    # RabbitMQ AMQP port
    networks:
        - app-network

networks:
  app-network:
    driver: bridge
