version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: fpm/Dockerfile
    container_name: php_app
    volumes:
        - ./app:/var/www/html/app
        - ./app/src/logs:/var/www/html/app/src/logs
    environment:
        - POSTGRES_HOST=${POSTGRES_HOST}
        - POSTGRES_DATABASE=${POSTGRES_DATABASE}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
        - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./app:/var/www/html/app
    ports:
        - "80:80"
        - "443:443"
    networks:
        - app-network
    depends_on:
        - app

networks:
  app-network:
    driver: bridge
